### ISSUE TITLE
Satellites in use / view information not updated when deactivating GPS

### ISSUE THREAD

**Issue by Pohli** [direc85/sailfish-gpsinfo#12]
After deactivating GPS from pulley menu and/or deactivating position from top menu Satellites in use / view still shows numbers different from 0.

Jolla Phone with SFOS 3.0.1.11 and GPSInfo 0.11

**Comment by direc85** [comment]
Yeah, the behavior is the same with XA2 and SFOS 3.2.0. I'll look into this soon.

**Comment by direc85** [comment]
Fixed in [873153e](https://github.com/direc85/harbour-gpsinfo/commit/873153e057be32157ad904b7cf43b031401bae10)
