### ISSUE TITLE
QChart missing from project and github clone

### ISSUE THREAD

**Issue by sbridger** [direc85/sailfish-gpsinfo#21]
QChart doesn't clone from github and QChart is not in the project file.

so unless  this can be fixed, these instructions should be added into the project somewhere:

What I did:
in folder QML -> git bash console
git clone <github url for chart.js>
move contents of new folder "chart.js" to folder QChart 
In QCreator, project treeview, At top "GPSINFO" right click -> "add existing directory" ->QChart

What you should theoretically need to do: (see https://gist.github.com/gitaarik/8735255):
```
git clone <gpsinfo url>
git submodule update --init
```
---
also changing

` Chart {`

to 

` QChart {` 

removes the unknown component error.

**Comment by direc85** [comment]
Doesn't it work with `git submodule init` and `git submodule update`?

**Comment by sbridger** [comment]
This is all new to me, so I have no idea.

The point is: I follow the generic github instructions i.e. `git clone xxxx`, and it doesn't work.

So, instructions are needed since it is a non-obvious git function + silent fault (because if you already have gpsinfo installed , it all works). 

Probably also put a note in the source where Chart is instantiated, as that is where the error message will send you.

**Comment by direc85** [comment]
I have to check the readme for this, but I'm afraid you are right - I'll have to update the little documentation there is. Using submodules is quite common these days, but I was in the same situation once too, so I understand your frustration.

Also, Chart element wasn't available until some later Qt version that SFOS uses, I think, but I could check it again and try to use it instead. (That could also explain why QChart was seemingly abandoned so quickly...)

**Comment by direc85** [comment]
Sorry for the delay... Okay, so there's no readme at all..! Gotta fix that :sweat_smile:

**Comment by direc85** [comment]
Fixed in [9c5de37](https://github.com/direc85/harbour-gpsinfo/commit/9c5de379af4dfd23b978aa592984841b459ed284)
