### ISSUE TITLE
Translation to Slovak is not active in app

### ISSUE THREAD

**Issue by okruhliak** [direc85/sailfish-gpsinfo#27]
Version 0.13.2-1, Xperia X
Slovak is missing from the list of languages ​​(Figure 1)   .
The application will not be set according to the SFOS environment (Slovak) (Figure 2).
   Slovak is listed in the list of translators (Figure 2 - "Slovenčina: okruhliak")
![figure1](https://user-images.githubusercontent.com/47862310/130325896-b5e87139-9283-4397-8ced-837243bd00a5.png)
![figure2](https://user-images.githubusercontent.com/47862310/130325901-955e7d51-59cd-470d-88f3-c843d5a005de.png)

**Comment by direc85** [comment]
That is indeed the case! This should be an easy fix.

**Comment by direc85** [comment]
Updated version is now released in OpenRepos.

**Comment by okruhliak** [comment]
I'm sorry, but the changes didn't show up in the app, everything is the same (v. 0.13.3-1).  Slovak is not in the list of languages, the application is in English (my mobile environment is Slovak).

**Comment by okruhliak** [comment]
Thank you very much, it's okay now :)

**Comment by direc85** [comment]
No problem! Thanks for reporting the issue, twice!

I really should have tested the first build. There I was, assuming things... :upside_down_face:
