### ISSUE TITLE
Translation of the points of the compass: East - West - North - South

### ISSUE THREAD

**Issue by okruhliak** [direc85/sailfish-gpsinfo#29]
Is it possible to translate E / W / S / N (attachment)?
![EWSN](https://user-images.githubusercontent.com/47862310/131249342-f1cee9a2-5ef0-4fae-8dd9-83025212ebbd.png)

**Comment by direc85** [comment]
Sorry for the delay! Fixed in [6c6df18](https://github.com/direc85/harbour-gpsinfo/commit/6c6df18cdaff2790e3dcee81454718c4f015bd62)
