### ISSUE TITLE
French translation, Line 162, "horizontale" should be "verticale"

### ISSUE THREAD

**Issue by Ric9k-TMO-FSO** [direc85/sailfish-gpsinfo#30]
Hi Matti,
Thanks for giving us access to this app!
All is in the title to ease for you.
My first time on Github, I hope this is the correct way to do...

Cheers,
Eric (Ric9k)

**Comment by direc85** [comment]
True enough! Fixed in e5c533cb53cae93f9bba80730f970d054e1373a6
