### ISSUE TITLE
the translation lacks the phrases: Time to First Fix / Direction / Calibration / Magnetic Declination

### ISSUE THREAD

**Issue by okruhliak** [direc85/sailfish-gpsinfo#31]

**Comment by direc85** [comment]
Thanks! Most of these were fixed in [6c6df18](https://github.com/direc85/harbour-gpsinfo/commit/6c6df18cdaff2790e3dcee81454718c4f015bd62) and the rest in [bece000](https://github.com/direc85/harbour-gpsinfo/commit/bece000539dc02c6ae12ba222d2f1e12ca53808c).
