### ISSUE TITLE
Suggestion: translate the orientation indications N / S / W / E

### ISSUE THREAD

**Issue by okruhliak** [direc85/sailfish-gpsinfo#32]
is it possible to include the orientation mark in the translation, please?

**Comment by direc85** [comment]
Thanks for suggestion! For Finnish, this doesn't make a lot of sense, but there it is :)

Fixed in [6c6df18](https://github.com/direc85/harbour-gpsinfo/commit/6c6df18cdaff2790e3dcee81454718c4f015bd62)
